using System.Collections;
using System.Collections.Generic;
using CharacterMatch3.Core;
using CharacterMatch3.Save;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace CharacterMatch3.UI
{
    public sealed class LevelMapUI : MonoBehaviour
    {
        private const int LevelsPerMapSection = 15;
        private const float NodeSize = 104f;
        private const float MarkerSize = 82f;
        private const float MapSectionHeight = 2340f;

        private static readonly Vector2[] FirstZonePositions =
        {
            new Vector2(600f, -2140f),
            new Vector2(570f, -1960f),
            new Vector2(645f, -1790f),
            new Vector2(580f, -1620f),
            new Vector2(640f, -1450f),
            new Vector2(575f, -1285f),
            new Vector2(635f, -1120f),
            new Vector2(565f, -965f),
            new Vector2(625f, -820f),
            new Vector2(570f, -670f),
            new Vector2(625f, -530f),
            new Vector2(585f, -400f),
            new Vector2(625f, -295f),
            new Vector2(560f, -205f),
            new Vector2(605f, -110f)
        };

        [Header("Generated by setup")]
        [SerializeField] private LevelLibrary levelLibrary;
        [SerializeField] private CharacterCatalog characterCatalog;

        [Header("Map Art Slots")]
        [SerializeField] private Sprite backgroundSprite;
        [SerializeField] private Sprite unlockedNodeSprite;
        [SerializeField] private Sprite currentNodeSprite;
        [SerializeField] private Sprite lockedNodeSprite;
        [SerializeField] private Sprite playerMarkerSprite;

        [Header("Progress Animation")]
        [SerializeField, Min(0.1f)] private float stepAnimationDuration = 0.75f;
        [SerializeField, Min(0f)] private float stepPauseDuration = 0.12f;

        private readonly Dictionary<int, LevelNodeView> nodeViews = new Dictionary<int, LevelNodeView>();
        private Canvas canvas;
        private RectTransform safeRoot;
        private RectTransform contentRoot;
        private ScrollRect scrollRect;
        private Image playerMarker;
        private Text progressLabel;
        private int maxLevelNumber;
        private int mapSectionCount;
        private bool progressionPlaying;

        private sealed class LevelNodeView
        {
            public int LevelNumber;
            public Button Button;
            public Image Image;
            public Text NumberLabel;
            public Text StarsLabel;
            public Text BadgeLabel;
        }

        private void Start()
        {
            RuntimeSceneUtility.EnsureMainCamera();
            Screen.orientation = ScreenOrientation.Portrait;
            SaveManager.Load();
            Build();
            StartCoroutine(PlayPendingProgressionIfNeeded());
        }

        public void Configure(LevelLibrary library, CharacterCatalog catalog)
        {
            levelLibrary = library;
            characterCatalog = catalog;
        }

        private void Build()
        {
            if (canvas != null)
            {
                return;
            }

            maxLevelNumber = CharacterMatch3Constants.LastLevel;
            mapSectionCount = Mathf.Max(1, Mathf.CeilToInt(maxLevelNumber / (float)LevelsPerMapSection));
            canvas = UIFactory.CreateCanvas("LevelMapCanvas");
            safeRoot = new GameObject("SafeArea", typeof(RectTransform), typeof(SafeAreaController)).GetComponent<RectTransform>();
            safeRoot.SetParent(canvas.transform, false);
            UIFactory.Stretch(safeRoot);

            UIFactory.CreatePanel("FallbackSky", safeRoot, new Color(0.36f, 0.76f, 0.96f));
            CreateScrollView(safeRoot);
            CreateMapBackgroundTiles();
            CreateLevelNodes();
            CreatePlayerMarker();
            CreateTopBar(safeRoot);
            CreateBottomBar(safeRoot);
            RefreshNodeStates();
            SnapScrollToLevel(GetInitialFocusLevel());
        }

        private void CreateTopBar(RectTransform safeRoot)
        {
            var titlePlate = UIFactory.CreatePanel("TitlePlate", safeRoot, new Color(1f, 0.9f, 0.66f, 0.96f));
            UIFactory.SetAnchored(titlePlate.GetComponent<RectTransform>(), new Vector2(0.12f, 0.89f), new Vector2(0.88f, 0.975f), Vector2.zero, Vector2.zero);

            var title = UIFactory.CreateText("Title", titlePlate.transform, "Adventure Map", 52, TextAnchor.MiddleCenter, new Color(0.35f, 0.15f, 0.04f));
            title.fontStyle = FontStyle.Bold;
            UIFactory.Stretch(title.rectTransform);

            var backButton = UIFactory.CreateButton("BackButton", safeRoot, "<", () =>
            {
                AudioManager.Instance?.PlayButton();
                SnapScrollToLevel(GetSelectedOrUnlockedLevel());
            });
            UIFactory.SetAnchored(backButton.GetComponent<RectTransform>(), new Vector2(0.035f, 0.91f), new Vector2(0.13f, 0.97f), Vector2.zero, Vector2.zero);
            backButton.GetComponent<Image>().color = new Color(0.23f, 0.66f, 0.94f, 0.98f);

            var currency = UIFactory.CreatePanel("Currency", safeRoot, new Color(1f, 0.86f, 0.48f, 0.96f));
            UIFactory.SetAnchored(currency.GetComponent<RectTransform>(), new Vector2(0.72f, 0.82f), new Vector2(0.96f, 0.875f), Vector2.zero, Vector2.zero);
            var currencyText = UIFactory.CreateText("CurrencyText", currency.transform, "1250 +", 30, TextAnchor.MiddleCenter, new Color(0.35f, 0.18f, 0.04f));
            currencyText.fontStyle = FontStyle.Bold;
            UIFactory.Stretch(currencyText.rectTransform);
        }

        private void CreateScrollView(RectTransform safeRoot)
        {
            var scrollObject = new GameObject("ScrollView", typeof(RectTransform), typeof(Image), typeof(ScrollRect), typeof(Mask));
            scrollObject.transform.SetParent(safeRoot, false);
            UIFactory.Stretch(scrollObject.GetComponent<RectTransform>());
            scrollObject.GetComponent<Image>().color = Color.white;
            scrollObject.GetComponent<Mask>().showMaskGraphic = false;

            contentRoot = new GameObject("Content", typeof(RectTransform)).GetComponent<RectTransform>();
            contentRoot.SetParent(scrollObject.transform, false);
            contentRoot.anchorMin = new Vector2(0f, 1f);
            contentRoot.anchorMax = new Vector2(1f, 1f);
            contentRoot.pivot = new Vector2(0.5f, 1f);
            contentRoot.anchoredPosition = Vector2.zero;
            contentRoot.sizeDelta = new Vector2(0f, MapSectionHeight * mapSectionCount);

            scrollRect = scrollObject.GetComponent<ScrollRect>();
            scrollRect.viewport = scrollObject.GetComponent<RectTransform>();
            scrollRect.content = contentRoot;
            scrollRect.horizontal = false;
            scrollRect.vertical = true;
            scrollRect.movementType = ScrollRect.MovementType.Clamped;
            scrollRect.inertia = true;
            scrollRect.scrollSensitivity = 34f;
        }

        private void CreateBottomBar(RectTransform safeRoot)
        {
            var bottomBar = UIFactory.CreatePanel("BottomBar", safeRoot, new Color(1f, 0.9f, 0.66f, 0.96f));
            UIFactory.SetAnchored(bottomBar.GetComponent<RectTransform>(), new Vector2(0f, 0f), new Vector2(1f, 0.08f), Vector2.zero, Vector2.zero);
            var mapText = UIFactory.CreateText("MapTab", bottomBar.transform, "Map", 30, TextAnchor.MiddleCenter, new Color(0.34f, 0.16f, 0.04f));
            mapText.fontStyle = FontStyle.Bold;
            UIFactory.Stretch(mapText.rectTransform);
        }

        private void CreateMapBackgroundTiles()
        {
            for (var section = 0; section < mapSectionCount; section++)
            {
                var tile = UIFactory.CreateImage($"MapBG_{section:00}", contentRoot, Color.white);
                tile.sprite = backgroundSprite;
                tile.preserveAspect = false;
                tile.raycastTarget = false;
                var rect = tile.rectTransform;
                rect.anchorMin = new Vector2(0f, 1f);
                rect.anchorMax = new Vector2(1f, 1f);
                rect.pivot = new Vector2(0.5f, 0.5f);
                rect.anchoredPosition = new Vector2(0f, -MapSectionHeight * section - MapSectionHeight * 0.5f);
                rect.sizeDelta = new Vector2(0f, MapSectionHeight);
            }
        }

        private void CreateLevelNodes()
        {
            nodeViews.Clear();
            for (var levelNumber = CharacterMatch3Constants.FirstLevel; levelNumber <= maxLevelNumber; levelNumber++)
            {
                var captured = levelNumber;
                var node = UIFactory.CreateButton($"Level_{levelNumber:000}", contentRoot, string.Empty, () => TryStartLevel(captured));
                var nodeRect = node.GetComponent<RectTransform>();
                nodeRect.anchorMin = new Vector2(0f, 1f);
                nodeRect.anchorMax = new Vector2(0f, 1f);
                nodeRect.pivot = new Vector2(0.5f, 0.5f);
                nodeRect.sizeDelta = new Vector2(NodeSize, NodeSize);
                nodeRect.anchoredPosition = GetLevelPosition(levelNumber);

                var image = node.GetComponent<Image>();
                var numberLabel = node.transform.Find("Label").GetComponent<Text>();
                numberLabel.fontStyle = FontStyle.Bold;
                numberLabel.fontSize = 44;
                numberLabel.resizeTextMaxSize = 44;

                var starsLabel = UIFactory.CreateText("Stars", node.transform, string.Empty, 24, TextAnchor.LowerCenter, new Color(0.4f, 0.24f, 0.02f));
                starsLabel.fontStyle = FontStyle.Bold;
                UIFactory.Stretch(starsLabel.rectTransform);

                var badgeLabel = UIFactory.CreateText("Badge", node.transform, string.Empty, 24, TextAnchor.UpperCenter, Color.white);
                badgeLabel.fontStyle = FontStyle.Bold;
                UIFactory.SetAnchored(badgeLabel.rectTransform, new Vector2(-0.18f, 0.82f), new Vector2(1.18f, 1.23f), Vector2.zero, Vector2.zero);

                nodeViews[levelNumber] = new LevelNodeView
                {
                    LevelNumber = levelNumber,
                    Button = node,
                    Image = image,
                    NumberLabel = numberLabel,
                    StarsLabel = starsLabel,
                    BadgeLabel = badgeLabel
                };
            }
        }

        private void CreatePlayerMarker()
        {
            playerMarker = UIFactory.CreateImage("PlayerMarker", contentRoot, new Color(1f, 0.92f, 0.24f, 1f));
            playerMarker.sprite = playerMarkerSprite != null
                ? playerMarkerSprite
                : characterCatalog != null
                    ? characterCatalog.GetSprite(CharacterType.Cat)
                    : null;
            playerMarker.preserveAspect = true;
            playerMarker.raycastTarget = false;

            var markerRect = playerMarker.rectTransform;
            markerRect.anchorMin = new Vector2(0f, 1f);
            markerRect.anchorMax = new Vector2(0f, 1f);
            markerRect.pivot = new Vector2(0.5f, 0.5f);
            markerRect.sizeDelta = new Vector2(MarkerSize, MarkerSize);

            progressLabel = UIFactory.CreateText("ProgressLabel", safeRoot, string.Empty, 34, TextAnchor.MiddleCenter, Color.white);
            progressLabel.fontStyle = FontStyle.Bold;
            progressLabel.raycastTarget = false;
            UIFactory.SetAnchored(progressLabel.rectTransform, new Vector2(0.1f, 0.89f), new Vector2(0.9f, 0.96f), Vector2.zero, Vector2.zero);

            PlaceMarkerAtLevel(GetInitialFocusLevel());
            playerMarker.transform.SetAsLastSibling();
            progressLabel.transform.SetAsLastSibling();
        }

        private void TryStartLevel(int levelNumber)
        {
            if (progressionPlaying || !CanPlayLevel(levelNumber) || !SaveManager.IsLevelUnlocked(levelNumber))
            {
                return;
            }

            AudioManager.Instance?.PlayButton();
            GameState.ClearMapProgression();
            GameState.SelectedLevelNumber = levelNumber;
            SceneManager.LoadScene("Gameplay");
        }

        private IEnumerator PlayPendingProgressionIfNeeded()
        {
            yield return null;
            Canvas.ForceUpdateCanvases();

            if (!GameState.HasPendingMapProgression)
            {
                RefreshNodeStates();
                SnapScrollToLevel(GetInitialFocusLevel());
                yield break;
            }

            var fromLevel = Mathf.Clamp(GameState.PendingMapProgressFrom, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            var toLevel = Mathf.Clamp(GameState.PendingMapProgressTo, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            if (toLevel <= fromLevel)
            {
                GameState.ClearMapProgression();
                yield break;
            }

            progressionPlaying = true;
            RefreshNodeStates();
            SnapScrollToLevel(fromLevel);
            PlaceMarkerAtLevel(fromLevel);
            progressLabel.text = $"Level {fromLevel} Complete!";
            yield return new WaitForSeconds(0.25f);

            for (var level = fromLevel; level < toLevel; level++)
            {
                yield return AnimateScrollToLevel(level + 1, 0.22f);
                yield return AnimateMarker(GetMarkerPosition(level), GetMarkerPosition(level + 1));
                GameState.SelectedLevelNumber = level + 1;
                RefreshNodeStates();
                yield return PulseNode(level + 1);
                yield return new WaitForSeconds(stepPauseDuration);
            }

            progressLabel.text = $"Level {toLevel} Unlocked";
            GameState.ClearMapProgression();
            progressionPlaying = false;
            RefreshNodeStates();
            yield return new WaitForSeconds(0.45f);
            progressLabel.text = string.Empty;
        }

        private IEnumerator AnimateMarker(Vector2 from, Vector2 to)
        {
            var markerRect = playerMarker.rectTransform;
            for (var elapsed = 0f; elapsed < stepAnimationDuration; elapsed += Time.unscaledDeltaTime)
            {
                var t = Mathf.Clamp01(elapsed / stepAnimationDuration);
                var eased = EaseInOut(t);
                var arc = Mathf.Sin(t * Mathf.PI) * 56f;
                markerRect.anchoredPosition = Vector2.Lerp(from, to, eased) + new Vector2(0f, arc);
                markerRect.localScale = Vector3.one * (1f + Mathf.Sin(t * Mathf.PI) * 0.12f);
                yield return null;
            }

            markerRect.anchoredPosition = to;
            markerRect.localScale = Vector3.one;
        }

        private IEnumerator PulseNode(int levelNumber)
        {
            if (!nodeViews.TryGetValue(levelNumber, out var view))
            {
                yield break;
            }

            var rect = view.Button.GetComponent<RectTransform>();
            for (var elapsed = 0f; elapsed < 0.32f; elapsed += Time.unscaledDeltaTime)
            {
                var t = Mathf.Clamp01(elapsed / 0.32f);
                rect.localScale = Vector3.one * (1f + Mathf.Sin(t * Mathf.PI) * 0.18f);
                yield return null;
            }

            rect.localScale = Vector3.one;
        }

        private IEnumerator AnimateScrollToLevel(int levelNumber, float duration)
        {
            if (scrollRect == null || contentRoot == null)
            {
                yield break;
            }

            Canvas.ForceUpdateCanvases();
            var start = contentRoot.anchoredPosition;
            var target = new Vector2(start.x, GetScrollYForLevel(levelNumber));
            for (var elapsed = 0f; elapsed < duration; elapsed += Time.unscaledDeltaTime)
            {
                var t = Mathf.Clamp01(elapsed / duration);
                contentRoot.anchoredPosition = Vector2.Lerp(start, target, EaseInOut(t));
                yield return null;
            }

            contentRoot.anchoredPosition = target;
        }

        private void RefreshNodeStates()
        {
            foreach (var pair in nodeViews)
            {
                var levelNumber = pair.Key;
                var view = pair.Value;
                var unlocked = CanPlayLevel(levelNumber) && SaveManager.IsLevelUnlocked(levelNumber);
                var current = unlocked && levelNumber == GetSelectedOrUnlockedLevel();
                var stars = SaveManager.GetStars(levelNumber);

                view.Button.interactable = unlocked && !progressionPlaying;
                view.Image.sprite = current && currentNodeSprite != null
                    ? currentNodeSprite
                    : unlocked && unlockedNodeSprite != null
                        ? unlockedNodeSprite
                        : !unlocked && lockedNodeSprite != null
                            ? lockedNodeSprite
                            : null;
                view.Image.color = unlocked
                    ? current
                        ? new Color(0.2f, 0.68f, 1f, 0.98f)
                        : new Color(0.46f, 0.82f, 0.16f, 0.98f)
                    : new Color(0.45f, 0.48f, 0.57f, 0.86f);

                view.NumberLabel.text = unlocked ? levelNumber.ToString() : "LOCK";
                view.NumberLabel.color = unlocked ? Color.white : new Color(0.9f, 0.86f, 0.78f);
                view.StarsLabel.text = unlocked && stars > 0 ? new string('*', stars) : string.Empty;
                view.BadgeLabel.text = current && !progressionPlaying ? "Play!" : string.Empty;
            }

            PlaceMarkerAtLevel(GetSelectedOrUnlockedLevel());
            playerMarker?.transform.SetAsLastSibling();
            progressLabel?.transform.SetAsLastSibling();
        }

        private void PlaceMarkerAtLevel(int levelNumber)
        {
            if (playerMarker == null)
            {
                return;
            }

            playerMarker.rectTransform.anchoredPosition = GetMarkerPosition(levelNumber);
        }

        private void SnapScrollToLevel(int levelNumber)
        {
            if (contentRoot == null)
            {
                return;
            }

            Canvas.ForceUpdateCanvases();
            var position = contentRoot.anchoredPosition;
            position.y = GetScrollYForLevel(levelNumber);
            contentRoot.anchoredPosition = position;
        }

        private float GetScrollYForLevel(int levelNumber)
        {
            var viewport = scrollRect != null && scrollRect.viewport != null ? scrollRect.viewport : (RectTransform)contentRoot.parent;
            var viewportHeight = viewport.rect.height > 1f ? viewport.rect.height : 1500f;
            var contentHeight = contentRoot.rect.height > 1f ? contentRoot.rect.height : contentRoot.sizeDelta.y;
            var levelPosition = GetLevelPosition(levelNumber);
            var target = -levelPosition.y - viewportHeight * 0.52f;
            return Mathf.Clamp(target, 0f, Mathf.Max(0f, contentHeight - viewportHeight));
        }

        private int GetInitialFocusLevel()
        {
            return Mathf.Clamp(GetSelectedOrUnlockedLevel(), CharacterMatch3Constants.FirstLevel, maxLevelNumber);
        }

        private int GetSelectedOrUnlockedLevel()
        {
            var selected = Mathf.Clamp(GameState.SelectedLevelNumber, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            if (CanPlayLevel(selected) && SaveManager.IsLevelUnlocked(selected))
            {
                return selected;
            }

            var highest = Mathf.Clamp(SaveManager.Data.highestUnlockedLevel, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            for (var levelNumber = highest; levelNumber >= CharacterMatch3Constants.FirstLevel; levelNumber--)
            {
                if (CanPlayLevel(levelNumber) && SaveManager.IsLevelUnlocked(levelNumber))
                {
                    return levelNumber;
                }
            }

            return CharacterMatch3Constants.FirstLevel;
        }

        private bool CanPlayLevel(int levelNumber)
        {
            return levelLibrary == null || levelLibrary.GetLevel(levelNumber) != null;
        }

        private Vector2 GetLevelPosition(int levelNumber)
        {
            var clamped = Mathf.Clamp(levelNumber, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            var zeroBased = clamped - CharacterMatch3Constants.FirstLevel;
            var sectionFromBottom = zeroBased / LevelsPerMapSection;
            var sectionFromTop = Mathf.Max(0, mapSectionCount - 1 - sectionFromBottom);
            var localIndex = zeroBased % LevelsPerMapSection;
            var localPosition = FirstZonePositions[localIndex];
            return localPosition + new Vector2(0f, -MapSectionHeight * sectionFromTop);
        }

        private Vector2 GetMarkerPosition(int levelNumber)
        {
            return GetLevelPosition(levelNumber) + new Vector2(0f, 82f);
        }

        private static float EaseInOut(float t)
        {
            return t * t * (3f - 2f * t);
        }
    }
}
