using System.Collections;
using System.Collections.Generic;
using CharacterMatch3.Core;
using CharacterMatch3.Save;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace CharacterMatch3.UI
{
    public sealed class LevelMapUI : MonoBehaviour
    {
        private const int LevelsPerMapSegment = 7;
        private const int SegmentThemeCount = 3;
        private const float NodeSize = 112f;
        private const float MarkerSize = 88f;
        private const float ReferenceMapWidth = 1080f;
        private const float FallbackMapSegmentHeight = 1920f;
        private const float MinimumMapSegmentHeight = 820f;
        private static readonly Vector2 SceneMarkerOffset = new Vector2(42f, 76f);
        private const char FilledStarCharacter = '\u2605';

        [Header("Generated by setup")]
        [SerializeField] private LevelLibrary levelLibrary;
        [SerializeField] private CharacterCatalog characterCatalog;

        [Header("Map Art Slots")]
        [SerializeField] private Sprite backgroundSprite;
        [SerializeField] private Sprite mapMeadowSprite;
        [SerializeField] private Sprite mapBeachSprite;
        [SerializeField] private Sprite mapDesertSprite;
        [SerializeField] private bool useSingleBackgroundSprite = true;
        [SerializeField] private Sprite unlockedNodeSprite;
        [SerializeField] private Sprite currentNodeSprite;
        [SerializeField] private Sprite completedNodeSprite;
        [SerializeField] private Sprite lockedNodeSprite;
        [SerializeField] private Sprite playerMarkerSprite;

        [Header("Scene Editable UI")]
        [Tooltip("Optional canvas placed in LevelMap.unity so the top UI can be seen and adjusted in Scene view.")]
        [SerializeField] private Canvas sceneCanvas;
        [SerializeField] private RectTransform sceneSafeRoot;
        [SerializeField] private RectTransform sceneMapPreviewRoot;
        [SerializeField] private RectTransform sceneTopBarRoot;
        [SerializeField] private Text sceneTitleText;
        [SerializeField] private Button sceneBackButton;
        [SerializeField] private Text sceneProgressText;

        [Header("Map Node Positions (0-1)")]
        [Tooltip("Levels 1-7. X is left/right, Y is top/bottom inside the forest map segment.")]
        [SerializeField]
        private Vector2[] forestLevelPositionFactors =
        {
            new Vector2(0.47f, 0.88f),
            new Vector2(0.43f, 0.73f),
            new Vector2(0.54f, 0.64f),
            new Vector2(0.5f, 0.49f),
            new Vector2(0.42f, 0.36f),
            new Vector2(0.56f, 0.24f),
            new Vector2(0.51f, 0.11f)
        };

        [Tooltip("Levels 8-14. X is left/right, Y is top/bottom inside the beach map segment.")]
        [SerializeField]
        private Vector2[] beachLevelPositionFactors =
        {
            new Vector2(0.45f, 0.7f),
            new Vector2(0.54f, 0.56f),
            new Vector2(0.42f, 0.43f),
            new Vector2(0.52f, 0.31f),
            new Vector2(0.47f, 0.2f),
            new Vector2(0.4f, 0.11f),
            new Vector2(0.5f, 0.04f)
        };

        [Tooltip("Levels 15-21, then reused for later desert sections. X is left/right, Y is top/bottom inside the desert map segment.")]
        [SerializeField]
        private Vector2[] desertLevelPositionFactors =
        {
            new Vector2(0.49f, 0.96f),
            new Vector2(0.56f, 0.88f),
            new Vector2(0.48f, 0.8f),
            new Vector2(0.56f, 0.72f),
            new Vector2(0.47f, 0.64f),
            new Vector2(0.54f, 0.56f),
            new Vector2(0.49f, 0.48f)
        };

        [Header("Continuous Map Slicing")]
        [SerializeField, Range(0.34f, 0.46f)] private float meadowSlicePercent = 0.36f;
        [SerializeField, Range(0.2f, 0.34f)] private float beachSlicePercent = 0.32f;
        [SerializeField, Range(0.04f, 0.08f)] private float mapSliceOverlapPercent = 0.05f;
        [SerializeField, Range(1f, 1.35f)] private float mapArtZoom = 1.18f;
        [SerializeField] private bool showBottomBar;

        [Header("Progress Animation")]
        [SerializeField, Min(0.1f)] private float stepAnimationDuration = 0.75f;
        [SerializeField, Min(0f)] private float stepPauseDuration = 0.12f;

        private readonly Dictionary<int, LevelNodeView> nodeViews = new Dictionary<int, LevelNodeView>();
        private Canvas canvas;
        private RectTransform safeRoot;
        private RectTransform contentRoot;
        private ScrollRect scrollRect;
        private Image playerMarker;
        private RectTransform playerMarkerRect;
        private Vector3 playerMarkerBaseScale = Vector3.one;
        private Text progressLabel;
        private RectTransform ambientSparkleRoot;
        private int maxLevelNumber;
        private int mapSectionCount;
        private int highlightedLevelNumber;
        private float[] segmentHeightsByBottom;
        private float[] segmentTopYByBottom;
        private float[] segmentWidthsByBottom;
        private float mapContentHeight;
        private float mapSegmentOverlapHeight;
        private bool usesSingleBackgroundLayout;
        private bool usesContinuousSliceLayout;
        private bool usesSceneEditableMap;
        private bool progressionPlaying;

        private sealed class LevelNodeView
        {
            public int LevelNumber;
            public RectTransform Rect;
            public Vector3 BaseScale;
            public Button Button;
            public Image Image;
            public Image Glow;
            public Image BadgePlate;
            public Text NumberLabel;
            public Text StarsLabel;
            public Text BadgeLabel;
        }

        private void Start()
        {
            RuntimeSceneUtility.EnsureMainCamera();
            Screen.orientation = ScreenOrientation.Portrait;
            SaveManager.Load();
            Build();
            StartCoroutine(PlayPendingProgressionIfNeeded());
        }

        private void Update()
        {
            AnimateCurrentLevelGlow();
            AnimateIdleMarker();
        }

        public void Configure(LevelLibrary library, CharacterCatalog catalog)
        {
            levelLibrary = library;
            characterCatalog = catalog;
        }

        private void Build()
        {
            if (canvas != null)
            {
                return;
            }

            maxLevelNumber = CharacterMatch3Constants.LastLevel;
            mapSectionCount = Mathf.Max(1, Mathf.CeilToInt(maxLevelNumber / (float)LevelsPerMapSegment));
            var usingSceneEditableMap = false;
            if (!TryUseSceneEditableShell())
            {
                canvas = UIFactory.CreateCanvas("LevelMapCanvas");
                safeRoot = new GameObject("SafeArea", typeof(RectTransform), typeof(SafeAreaController)).GetComponent<RectTransform>();
                safeRoot.SetParent(canvas.transform, false);
                UIFactory.Stretch(safeRoot);
            }
            else
            {
                usingSceneEditableMap = TryUseSceneEditableMapViewport();
            }
            usesSceneEditableMap = usingSceneEditableMap;

            if (usingSceneEditableMap)
            {
                BindSceneEditableMapNodes();
                BindSceneEditablePlayerMarker();
            }
            else
            {
                UIFactory.CreatePanel("FallbackSky", safeRoot, new Color(0.36f, 0.76f, 0.96f));
                CreateScrollView(safeRoot);
                CalculateSegmentLayout();
                CreateMapBackgroundTiles();
                CreateLevelNodes();
                CreatePlayerMarker();
                CreateAmbientSparkles(safeRoot);
            }

            CreateTopBar(safeRoot);
            if (showBottomBar)
            {
                CreateBottomBar(safeRoot);
            }
            if (usingSceneEditableMap)
            {
                RefreshSceneEditableMapButtons();
            }
            else
            {
                RefreshNodeStates();
                SnapScrollToLevel(GetInitialFocusLevel());
            }
        }

        private void CreateTopBar(RectTransform safeRoot)
        {
            if (TryUseSceneEditableTopBar())
            {
                return;
            }

            var titlePlate = UIFactory.CreatePanel("TitlePlate", safeRoot, new Color(1f, 0.9f, 0.66f, 0.96f));
            UIFactory.SetAnchored(titlePlate.GetComponent<RectTransform>(), new Vector2(0.12f, 0.89f), new Vector2(0.88f, 0.975f), Vector2.zero, Vector2.zero);
            var titleShadow = titlePlate.AddComponent<Shadow>();
            titleShadow.effectColor = new Color(0.18f, 0.1f, 0.04f, 0.24f);
            titleShadow.effectDistance = new Vector2(0f, -5f);

            var title = UIFactory.CreateText("Title", titlePlate.transform, "Lumiko Map", 52, TextAnchor.MiddleCenter, new Color(0.35f, 0.15f, 0.04f));
            title.fontStyle = FontStyle.Bold;
            UIFactory.Stretch(title.rectTransform);

            var backButton = UIFactory.CreateButton("BackButton", safeRoot, "<", HandleBackButtonClicked);
            UIFactory.SetAnchored(backButton.GetComponent<RectTransform>(), new Vector2(0.035f, 0.91f), new Vector2(0.13f, 0.97f), Vector2.zero, Vector2.zero);
            SetButtonColors(backButton, new Color(0.23f, 0.66f, 0.94f, 0.98f), Color.white);

            var progress = UIFactory.CreatePanel("LevelProgress", safeRoot, new Color(1f, 0.86f, 0.48f, 0.96f));
            UIFactory.SetAnchored(progress.GetComponent<RectTransform>(), new Vector2(0.69f, 0.82f), new Vector2(0.96f, 0.875f), Vector2.zero, Vector2.zero);
            var progressText = UIFactory.CreateText("ProgressText", progress.transform, $"Level {GetSelectedOrUnlockedLevel()}/{maxLevelNumber}", 27, TextAnchor.MiddleCenter, new Color(0.35f, 0.18f, 0.04f));
            progressText.fontStyle = FontStyle.Bold;
            UIFactory.Stretch(progressText.rectTransform);
        }

        private bool TryUseSceneEditableShell()
        {
            if (sceneCanvas == null || sceneSafeRoot == null)
            {
                return false;
            }

            canvas = sceneCanvas;
            safeRoot = sceneSafeRoot;
            ConfigureSceneCanvas(canvas);
            UIFactory.EnsureEventSystem();
            return true;
        }

        private bool TryUseSceneEditableTopBar()
        {
            ResolveSceneTopBarReferences();
            if (sceneTopBarRoot == null && sceneTitleText == null && sceneBackButton == null && sceneProgressText == null)
            {
                return false;
            }

            if (sceneTopBarRoot != null)
            {
                sceneTopBarRoot.gameObject.SetActive(true);
                sceneTopBarRoot.SetAsLastSibling();
            }

            if (sceneTitleText != null && string.IsNullOrWhiteSpace(sceneTitleText.text))
            {
                sceneTitleText.text = "Lumiko Map";
            }

            if (sceneProgressText != null)
            {
                sceneProgressText.text = $"Level {GetSelectedOrUnlockedLevel()}/{maxLevelNumber}";
            }

            if (sceneBackButton != null)
            {
                sceneBackButton.onClick.RemoveListener(HandleBackButtonClicked);
                sceneBackButton.onClick.AddListener(HandleBackButtonClicked);
                if (sceneBackButton.GetComponent<ButtonPressAnimator>() == null)
                {
                    sceneBackButton.gameObject.AddComponent<ButtonPressAnimator>();
                }
            }

            return true;
        }

        private void ResolveSceneTopBarReferences()
        {
            if (sceneTopBarRoot == null)
            {
                return;
            }

            sceneBackButton ??= FindChildComponentByName<Button>(sceneTopBarRoot, "BackButton");
            sceneTitleText ??= FindChildComponentByName<Text>(sceneTopBarRoot, "Title");
            sceneProgressText ??= FindChildComponentByName<Text>(sceneTopBarRoot, "ProgressText");
        }

        private void HandleBackButtonClicked()
        {
            AudioManager.Instance?.PlayButton();
            if (usesSceneEditableMap)
            {
                return;
            }

            SnapScrollToLevel(GetSelectedOrUnlockedLevel());
        }

        private static void ConfigureSceneCanvas(Canvas targetCanvas)
        {
            if (targetCanvas == null)
            {
                return;
            }

            targetCanvas.renderMode = RenderMode.ScreenSpaceOverlay;
            var scaler = targetCanvas.GetComponent<CanvasScaler>();
            if (scaler != null)
            {
                scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
                scaler.referenceResolution = new Vector2(1080, 1920);
                scaler.matchWidthOrHeight = 0.5f;
            }
        }

        private static T FindChildComponentByName<T>(Transform root, string childName) where T : Component
        {
            if (root == null)
            {
                return null;
            }

            var children = root.GetComponentsInChildren<T>(true);
            foreach (var child in children)
            {
                if (child.name == childName)
                {
                    return child;
                }
            }

            return null;
        }

        private void CreateScrollView(RectTransform safeRoot)
        {
            var scrollObject = new GameObject("ScrollView", typeof(RectTransform), typeof(Image), typeof(ScrollRect), typeof(Mask));
            scrollObject.transform.SetParent(safeRoot, false);
            UIFactory.Stretch(scrollObject.GetComponent<RectTransform>());
            scrollObject.GetComponent<Image>().color = Color.white;
            scrollObject.GetComponent<Mask>().showMaskGraphic = false;

            contentRoot = new GameObject("Content", typeof(RectTransform)).GetComponent<RectTransform>();
            contentRoot.SetParent(scrollObject.transform, false);
            ConfigureRuntimeMapContent(contentRoot);

            scrollRect = scrollObject.GetComponent<ScrollRect>();
            ConfigureScrollRect(scrollRect, scrollObject.GetComponent<RectTransform>(), contentRoot);
        }

        private bool TryUseSceneEditableMapViewport()
        {
            if (sceneMapPreviewRoot == null)
            {
                return false;
            }

            contentRoot = FindSceneMapContentRoot(sceneMapPreviewRoot);
            if (contentRoot == null)
            {
                return false;
            }

            sceneMapPreviewRoot.gameObject.SetActive(true);
            sceneMapPreviewRoot.SetAsLastSibling();

            var viewportImage = sceneMapPreviewRoot.GetComponent<Image>();
            if (viewportImage == null)
            {
                viewportImage = sceneMapPreviewRoot.gameObject.AddComponent<Image>();
            }

            viewportImage.color = Color.white;
            viewportImage.raycastTarget = true;

            var viewportMask = sceneMapPreviewRoot.GetComponent<Mask>();
            if (viewportMask == null)
            {
                viewportMask = sceneMapPreviewRoot.gameObject.AddComponent<Mask>();
            }

            viewportMask.showMaskGraphic = false;

            scrollRect = sceneMapPreviewRoot.GetComponent<ScrollRect>();
            if (scrollRect == null)
            {
                scrollRect = sceneMapPreviewRoot.gameObject.AddComponent<ScrollRect>();
            }

            ConfigureScrollRect(scrollRect, sceneMapPreviewRoot, contentRoot);
            mapContentHeight = Mathf.Max(FallbackMapSegmentHeight, Mathf.Abs(contentRoot.sizeDelta.y));
            return true;
        }

        private static RectTransform FindSceneMapContentRoot(Transform root)
        {
            var content = root.Find("Content") ?? root.Find("Preview Map Content");
            return content != null ? content as RectTransform : null;
        }

        private static void ConfigureRuntimeMapContent(RectTransform target)
        {
            target.anchorMin = new Vector2(0f, 1f);
            target.anchorMax = new Vector2(1f, 1f);
            target.pivot = new Vector2(0.5f, 1f);
            target.anchoredPosition = Vector2.zero;
            target.sizeDelta = new Vector2(0f, FallbackMapSegmentHeight);
            target.localScale = Vector3.one;
        }

        private static void ConfigureScrollRect(ScrollRect target, RectTransform viewport, RectTransform content)
        {
            target.viewport = viewport;
            target.content = content;
            target.horizontal = false;
            target.vertical = true;
            target.movementType = ScrollRect.MovementType.Clamped;
            target.inertia = true;
            target.scrollSensitivity = 34f;
        }

        private void BindSceneEditableMapNodes()
        {
            nodeViews.Clear();
            if (contentRoot == null)
            {
                return;
            }

            for (var levelNumber = CharacterMatch3Constants.FirstLevel; levelNumber <= maxLevelNumber; levelNumber++)
            {
                var node = FindSceneEditableLevelNode(levelNumber);
                if (node == null)
                {
                    continue;
                }

                var captured = levelNumber;
                var button = node.GetComponent<Button>();
                if (button == null)
                {
                    button = node.gameObject.AddComponent<Button>();
                }

                button.transition = Selectable.Transition.None;
                var graphic = node.GetComponent<Graphic>();
                if (graphic != null)
                {
                    graphic.raycastTarget = true;
                }

                button.targetGraphic = graphic;
                button.onClick.RemoveAllListeners();
                button.onClick.AddListener(() => TryStartLevel(captured));

                nodeViews[levelNumber] = new LevelNodeView
                {
                    LevelNumber = levelNumber,
                    Rect = node,
                    BaseScale = node.localScale,
                    Button = button,
                    Image = node.GetComponent<Image>(),
                    NumberLabel = FindChildComponentByName<Text>(node, "Number"),
                    StarsLabel = FindChildComponentByName<Text>(node, "Stars"),
                    BadgeLabel = FindChildComponentByName<Text>(node, "Badge")
                };
            }
        }

        private void BindSceneEditablePlayerMarker()
        {
            var marker = FindDeepChildByName(contentRoot, "PreviewPlayerMarker") as RectTransform;
            if (marker == null)
            {
                return;
            }

            playerMarkerRect = marker;
            playerMarker = marker.GetComponent<Image>();
            playerMarkerBaseScale = marker.localScale;
            PlaceMarkerAtLevel(GetInitialFocusLevel());
        }

        private void RefreshSceneEditableMapButtons()
        {
            foreach (var pair in nodeViews)
            {
                if (pair.Value.Button == null)
                {
                    continue;
                }

                var levelNumber = pair.Key;
                pair.Value.Button.interactable = CanPlayLevel(levelNumber) && SaveManager.IsLevelUnlocked(levelNumber);
            }
        }

        private RectTransform FindSceneEditableLevelNode(int levelNumber)
        {
            var exactName = $"PreviewLevel_{levelNumber:000}";
            var node = contentRoot.Find($"Preview Level Nodes/{exactName}") ?? FindDeepChildByName(contentRoot, exactName);
            return node as RectTransform;
        }

        private static Transform FindDeepChildByName(Transform root, string childName)
        {
            if (root == null)
            {
                return null;
            }

            foreach (Transform child in root)
            {
                if (child.name == childName)
                {
                    return child;
                }

                var nested = FindDeepChildByName(child, childName);
                if (nested != null)
                {
                    return nested;
                }
            }

            return null;
        }

        private void CreateBottomBar(RectTransform safeRoot)
        {
            var bottomBar = UIFactory.CreatePanel("BottomBar", safeRoot, new Color(1f, 0.9f, 0.66f, 0.96f));
            UIFactory.SetAnchored(bottomBar.GetComponent<RectTransform>(), new Vector2(0f, 0f), new Vector2(1f, 0.08f), Vector2.zero, Vector2.zero);
            var mapText = UIFactory.CreateText("MapTab", bottomBar.transform, "Map", 30, TextAnchor.MiddleCenter, new Color(0.34f, 0.16f, 0.04f));
            mapText.fontStyle = FontStyle.Bold;
            UIFactory.Stretch(mapText.rectTransform);
        }

        private void CreateMapBackgroundTiles()
        {
            for (var segmentFromBottom = mapSectionCount - 1; segmentFromBottom >= 0; segmentFromBottom--)
            {
                var tile = CreateMapBackgroundTile($"MapSegment_{GetSegmentThemeName(segmentFromBottom)}_{segmentFromBottom:00}", segmentFromBottom);
                var rect = tile.rectTransform;
                rect.anchorMin = new Vector2(0.5f, 1f);
                rect.anchorMax = new Vector2(0.5f, 1f);
                rect.pivot = new Vector2(0.5f, 0.5f);
                var height = GetSegmentHeight(segmentFromBottom);
                rect.anchoredPosition = new Vector2(0f, GetSegmentTopY(segmentFromBottom) - height * 0.5f);
                rect.sizeDelta = new Vector2(GetSegmentWidth(segmentFromBottom), height);
            }
        }

        private Graphic CreateMapBackgroundTile(string name, int segmentFromBottom)
        {
            if (usesSingleBackgroundLayout)
            {
                var tileObject = new GameObject(name, typeof(RectTransform), typeof(RawImage));
                tileObject.transform.SetParent(contentRoot, false);
                var rawImage = tileObject.GetComponent<RawImage>();
                rawImage.texture = backgroundSprite.texture;
                rawImage.uvRect = GetSingleBackgroundUvRect(segmentFromBottom);
                rawImage.color = Color.white;
                rawImage.raycastTarget = false;
                return rawImage;
            }

            var tile = UIFactory.CreateImage(name, contentRoot, Color.white);
            tile.sprite = GetSegmentSprite(segmentFromBottom);
            tile.preserveAspect = true;
            tile.raycastTarget = false;
            return tile;
        }

        private void CalculateSegmentLayout()
        {
            segmentHeightsByBottom = new float[mapSectionCount];
            segmentTopYByBottom = new float[mapSectionCount];
            segmentWidthsByBottom = new float[mapSectionCount];
            ClampSliceInspectorValues();
            usesSingleBackgroundLayout = HasSingleBackgroundSprite();
            usesContinuousSliceLayout = !usesSingleBackgroundLayout && HasContinuousSliceSprites();

            Canvas.ForceUpdateCanvases();
            var viewportWidth = GetMapViewportWidth();
            var mapArtScale = usesSingleBackgroundLayout
                ? GetSingleBackgroundScale(viewportWidth)
                : usesContinuousSliceLayout
                    ? GetContinuousMapScale(viewportWidth)
                    : 0f;
            mapSegmentOverlapHeight = GetSegmentOverlapHeight(viewportWidth, mapArtScale);

            var topOffset = 0f;
            for (var segmentFromBottom = mapSectionCount - 1; segmentFromBottom >= 0; segmentFromBottom--)
            {
                var sprite = GetSegmentSprite(segmentFromBottom);
                var width = viewportWidth;
                var height = FallbackMapSegmentHeight;

                if (usesSingleBackgroundLayout)
                {
                    var texture = backgroundSprite.texture;
                    width = Mathf.Max(viewportWidth, texture.width * mapArtScale);
                    height = texture.height * GetSingleBackgroundUvRect(segmentFromBottom).height * mapArtScale;
                }
                else if (sprite != null && sprite.rect.width > 1f && sprite.rect.height > 1f)
                {
                    var scale = usesContinuousSliceLayout
                        ? mapArtScale
                        : Mathf.Max(viewportWidth / sprite.rect.width, MinimumMapSegmentHeight / sprite.rect.height);
                    width = Mathf.Max(viewportWidth, sprite.rect.width * scale);
                    height = sprite.rect.height * scale;
                }

                segmentWidthsByBottom[segmentFromBottom] = width;
                segmentHeightsByBottom[segmentFromBottom] = height;
                segmentTopYByBottom[segmentFromBottom] = -topOffset;
                topOffset += height;

                if (segmentFromBottom > 0)
                {
                    topOffset -= Mathf.Min(mapSegmentOverlapHeight, height * 0.35f);
                }
            }

            mapContentHeight = Mathf.Max(FallbackMapSegmentHeight, topOffset);
            contentRoot.sizeDelta = new Vector2(0f, mapContentHeight);
        }

        private void ClampSliceInspectorValues()
        {
            meadowSlicePercent = Mathf.Clamp(meadowSlicePercent, 0.34f, 0.46f);
            beachSlicePercent = Mathf.Clamp(beachSlicePercent, 0.2f, Mathf.Min(0.34f, 0.92f - meadowSlicePercent));
            mapSliceOverlapPercent = Mathf.Clamp(mapSliceOverlapPercent, 0.04f, 0.08f);
            mapArtZoom = Mathf.Clamp(mapArtZoom, 1f, 1.35f);
        }

        private bool HasContinuousSliceSprites()
        {
            return mapMeadowSprite != null &&
                   mapBeachSprite != null &&
                   mapDesertSprite != null &&
                   mapMeadowSprite.texture == mapBeachSprite.texture &&
                   mapBeachSprite.texture == mapDesertSprite.texture;
        }

        private bool HasSingleBackgroundSprite()
        {
            return useSingleBackgroundSprite &&
                   backgroundSprite != null &&
                   backgroundSprite.texture != null &&
                   backgroundSprite.texture.width > 0 &&
                   backgroundSprite.texture.height > 0;
        }

        private float GetSingleBackgroundScale(float viewportWidth)
        {
            return viewportWidth / backgroundSprite.texture.width * mapArtZoom;
        }

        private float GetContinuousMapScale(float viewportWidth)
        {
            var sprite = mapMeadowSprite != null ? mapMeadowSprite : mapBeachSprite != null ? mapBeachSprite : mapDesertSprite;
            if (sprite == null || sprite.texture == null || sprite.texture.width <= 0 || sprite.texture.height <= 0)
            {
                return 1f;
            }

            return viewportWidth / sprite.texture.width * mapArtZoom;
        }

        private float GetSegmentOverlapHeight(float viewportWidth, float continuousScale)
        {
            var overlapPercent = Mathf.Clamp(mapSliceOverlapPercent, 0.04f, 0.08f);
            if (usesSingleBackgroundLayout)
            {
                return backgroundSprite.texture.height * overlapPercent * continuousScale;
            }

            if (usesContinuousSliceLayout)
            {
                var sprite = mapMeadowSprite != null ? mapMeadowSprite : mapBeachSprite != null ? mapBeachSprite : mapDesertSprite;
                if (sprite != null && sprite.texture != null)
                {
                    return sprite.texture.height * overlapPercent * continuousScale;
                }
            }

            return Mathf.Max(16f, viewportWidth * overlapPercent);
        }

        private float GetMapViewportWidth()
        {
            if (scrollRect != null && scrollRect.viewport != null && scrollRect.viewport.rect.width > 1f)
            {
                return scrollRect.viewport.rect.width;
            }

            if (contentRoot != null && contentRoot.rect.width > 1f)
            {
                return contentRoot.rect.width;
            }

            return ReferenceMapWidth;
        }

        private float GetSegmentHeight(int segmentFromBottom)
        {
            return segmentHeightsByBottom != null &&
                   segmentFromBottom >= 0 &&
                   segmentFromBottom < segmentHeightsByBottom.Length
                ? segmentHeightsByBottom[segmentFromBottom]
                : FallbackMapSegmentHeight;
        }

        private float GetSegmentWidth(int segmentFromBottom)
        {
            return segmentWidthsByBottom != null &&
                   segmentFromBottom >= 0 &&
                   segmentFromBottom < segmentWidthsByBottom.Length
                ? segmentWidthsByBottom[segmentFromBottom]
                : GetMapViewportWidth();
        }

        private float GetSegmentTopY(int segmentFromBottom)
        {
            if (segmentTopYByBottom != null &&
                segmentFromBottom >= 0 &&
                segmentFromBottom < segmentTopYByBottom.Length)
            {
                return segmentTopYByBottom[segmentFromBottom];
            }

            var sectionFromTop = Mathf.Max(0, mapSectionCount - 1 - segmentFromBottom);
            return -sectionFromTop * (FallbackMapSegmentHeight - FallbackMapSegmentHeight * Mathf.Clamp(mapSliceOverlapPercent, 0.04f, 0.08f));
        }

        private Rect GetSingleBackgroundUvRect(int segmentFromBottom)
        {
            var halfOverlap = Mathf.Clamp(mapSliceOverlapPercent, 0.04f, 0.08f) * 0.5f;
            var meadowEnd = Mathf.Clamp01(meadowSlicePercent + halfOverlap);
            var beachStart = Mathf.Clamp01(meadowSlicePercent - halfOverlap);
            var beachEnd = Mathf.Clamp01(meadowSlicePercent + beachSlicePercent + halfOverlap);
            var desertStart = Mathf.Clamp01(meadowSlicePercent + beachSlicePercent - halfOverlap);

            return GetSegmentThemeIndex(segmentFromBottom) switch
            {
                0 => new Rect(0f, 0f, 1f, Mathf.Max(0.01f, meadowEnd)),
                1 => new Rect(0f, beachStart, 1f, Mathf.Max(0.01f, beachEnd - beachStart)),
                2 => new Rect(0f, desertStart, 1f, Mathf.Max(0.01f, 1f - desertStart)),
                _ => new Rect(0f, 0f, 1f, 1f)
            };
        }

        private Sprite GetSegmentSprite(int segmentFromBottom)
        {
            var themedSprite = GetSegmentThemeIndex(segmentFromBottom) switch
            {
                0 => mapMeadowSprite,
                1 => mapBeachSprite,
                2 => mapDesertSprite,
                _ => null
            };

            return themedSprite != null ? themedSprite : backgroundSprite;
        }

        private static string GetSegmentThemeName(int segmentFromBottom)
        {
            return GetSegmentThemeIndex(segmentFromBottom) switch
            {
                0 => "Meadow",
                1 => "Beach",
                2 => "Desert",
                _ => "Map"
            };
        }

        private static int GetSegmentThemeIndex(int segmentFromBottom)
        {
            return Mathf.Clamp(segmentFromBottom, 0, SegmentThemeCount - 1);
        }

        private void CreateLevelNodes()
        {
            nodeViews.Clear();
            for (var levelNumber = CharacterMatch3Constants.FirstLevel; levelNumber <= maxLevelNumber; levelNumber++)
            {
                var captured = levelNumber;
                var node = UIFactory.CreateButton($"Level_{levelNumber:000}", contentRoot, string.Empty, () => TryStartLevel(captured));
                node.transition = Selectable.Transition.None;
                var nodeRect = node.GetComponent<RectTransform>();
                nodeRect.anchorMin = new Vector2(0f, 1f);
                nodeRect.anchorMax = new Vector2(0f, 1f);
                nodeRect.pivot = new Vector2(0.5f, 0.5f);
                nodeRect.sizeDelta = new Vector2(NodeSize, NodeSize);
                nodeRect.anchoredPosition = GetLevelPosition(levelNumber);

                var image = node.GetComponent<Image>();
                image.preserveAspect = true;
                var nodeShadow = node.gameObject.AddComponent<Shadow>();
                nodeShadow.effectColor = new Color(0.08f, 0.06f, 0.04f, 0.28f);
                nodeShadow.effectDistance = new Vector2(0f, -7f);

                var glow = UIFactory.CreateImage("Glow", node.transform, Color.clear);
                glow.raycastTarget = false;
                UIFactory.SetAnchored(glow.rectTransform, new Vector2(-0.16f, -0.16f), new Vector2(1.16f, 1.16f), Vector2.zero, Vector2.zero);
                glow.transform.SetAsFirstSibling();

                var numberLabel = node.transform.Find("Label").GetComponent<Text>();
                numberLabel.fontStyle = FontStyle.Bold;
                numberLabel.fontSize = 48;
                numberLabel.resizeTextMaxSize = 48;

                var starPlate = UIFactory.CreatePanel("StarPlate", node.transform, new Color(0.16f, 0.1f, 0.04f, 0.52f));
                starPlate.GetComponent<Image>().raycastTarget = false;
                UIFactory.SetAnchored(starPlate.GetComponent<RectTransform>(), new Vector2(-0.18f, -0.14f), new Vector2(1.18f, 0.13f), Vector2.zero, Vector2.zero);

                var starsLabel = UIFactory.CreateText("Stars", node.transform, string.Empty, 34, TextAnchor.MiddleCenter, new Color(1f, 0.86f, 0.18f));
                starsLabel.fontStyle = FontStyle.Bold;
                starsLabel.resizeTextMinSize = 20;
                starsLabel.resizeTextMaxSize = 34;
                UIFactory.SetAnchored(starsLabel.rectTransform, new Vector2(-0.16f, -0.22f), new Vector2(1.16f, 0.2f), Vector2.zero, Vector2.zero);
                var starsOutline = starsLabel.gameObject.AddComponent<Outline>();
                starsOutline.effectColor = new Color(0.28f, 0.16f, 0.03f, 0.9f);
                starsOutline.effectDistance = new Vector2(2f, -2f);

                var badgePlate = UIFactory.CreatePanel("BadgePlate", node.transform, new Color(0.24f, 0.58f, 0.92f, 0.94f));
                badgePlate.GetComponent<Image>().raycastTarget = false;
                UIFactory.SetAnchored(badgePlate.GetComponent<RectTransform>(), new Vector2(-0.12f, 0.86f), new Vector2(1.12f, 1.2f), Vector2.zero, Vector2.zero);

                var badgeLabel = UIFactory.CreateText("Badge", node.transform, string.Empty, 27, TextAnchor.UpperCenter, Color.white);
                badgeLabel.fontStyle = FontStyle.Bold;
                UIFactory.SetAnchored(badgeLabel.rectTransform, new Vector2(-0.18f, 0.82f), new Vector2(1.18f, 1.23f), Vector2.zero, Vector2.zero);

                nodeViews[levelNumber] = new LevelNodeView
                {
                    LevelNumber = levelNumber,
                    Rect = nodeRect,
                    BaseScale = nodeRect.localScale,
                    Button = node,
                    Image = image,
                    Glow = glow,
                    BadgePlate = badgePlate.GetComponent<Image>(),
                    NumberLabel = numberLabel,
                    StarsLabel = starsLabel,
                    BadgeLabel = badgeLabel
                };
            }
        }

        private void CreatePlayerMarker()
        {
            playerMarker = UIFactory.CreateImage("PlayerMarker", contentRoot, new Color(1f, 0.92f, 0.24f, 1f));
            playerMarker.sprite = playerMarkerSprite != null
                ? playerMarkerSprite
                : characterCatalog != null
                    ? characterCatalog.GetSprite(CharacterType.Bear)
                    : null;
            playerMarker.preserveAspect = true;
            playerMarker.raycastTarget = false;

            var markerRect = playerMarker.rectTransform;
            playerMarkerRect = markerRect;
            playerMarkerBaseScale = markerRect.localScale;
            markerRect.anchorMin = new Vector2(0f, 1f);
            markerRect.anchorMax = new Vector2(0f, 1f);
            markerRect.pivot = new Vector2(0.5f, 0.5f);
            markerRect.sizeDelta = new Vector2(MarkerSize, MarkerSize);

            progressLabel = UIFactory.CreateText("ProgressLabel", safeRoot, string.Empty, 34, TextAnchor.MiddleCenter, Color.white);
            progressLabel.fontStyle = FontStyle.Bold;
            progressLabel.raycastTarget = false;
            UIFactory.SetAnchored(progressLabel.rectTransform, new Vector2(0.1f, 0.89f), new Vector2(0.9f, 0.96f), Vector2.zero, Vector2.zero);

            PlaceMarkerAtLevel(GetInitialFocusLevel());
            playerMarker.transform.SetAsLastSibling();
            progressLabel.transform.SetAsLastSibling();
        }

        private void CreateAmbientSparkles(RectTransform parent)
        {
            if (ambientSparkleRoot != null)
            {
                return;
            }

            ambientSparkleRoot = new GameObject("AmbientSparkles", typeof(RectTransform), typeof(CanvasGroup)).GetComponent<RectTransform>();
            ambientSparkleRoot.SetParent(parent, false);
            UIFactory.Stretch(ambientSparkleRoot);
            var group = ambientSparkleRoot.GetComponent<CanvasGroup>();
            group.blocksRaycasts = false;
            group.interactable = false;
            StartCoroutine(AnimateAmbientSparkles());
        }

        private IEnumerator AnimateAmbientSparkles()
        {
            const int count = 18;
            var rects = new RectTransform[count];
            var images = new Image[count];
            var centers = new Vector2[count];
            var phases = new float[count];
            var random = new System.Random(2407);

            for (var i = 0; i < count; i++)
            {
                var sparkle = UIFactory.CreateImage($"Sparkle_{i:00}", ambientSparkleRoot, GetSparkleColor(i));
                sparkle.raycastTarget = false;
                var rect = sparkle.rectTransform;
                rect.anchorMin = new Vector2(0.5f, 0.5f);
                rect.anchorMax = new Vector2(0.5f, 0.5f);
                rect.pivot = new Vector2(0.5f, 0.5f);
                rect.sizeDelta = Vector2.one * (9f + i % 4 * 3f);
                rects[i] = rect;
                images[i] = sparkle;
                centers[i] = new Vector2((float)(random.NextDouble() * 880f - 440f), (float)(random.NextDouble() * 1380f - 690f));
                phases[i] = (float)random.NextDouble() * Mathf.PI * 2f;
            }

            while (ambientSparkleRoot != null)
            {
                var time = Time.unscaledTime;
                for (var i = 0; i < count; i++)
                {
                    if (rects[i] == null || images[i] == null)
                    {
                        continue;
                    }

                    var bob = Mathf.Sin(time * (0.65f + i * 0.03f) + phases[i]);
                    rects[i].anchoredPosition = centers[i] + new Vector2(Mathf.Sin(time * 0.28f + i) * 22f, bob * 18f);
                    rects[i].localRotation = Quaternion.Euler(0f, 0f, time * (28f + i % 5 * 6f));
                    rects[i].localScale = Vector3.one * (0.76f + Mathf.Abs(bob) * 0.42f);
                    var color = images[i].color;
                    color.a = 0.18f + Mathf.Abs(bob) * 0.28f;
                    images[i].color = color;
                }

                yield return null;
            }
        }

        private void TryStartLevel(int levelNumber)
        {
            if (progressionPlaying || !CanPlayLevel(levelNumber) || !SaveManager.IsLevelUnlocked(levelNumber))
            {
                return;
            }

            AudioManager.Instance?.PlayButton();
            GameState.ClearMapProgression();
            GameState.ClearMapStarReveal();
            GameState.SelectedLevelNumber = levelNumber;
            SceneManager.LoadScene("Gameplay");
        }

        private IEnumerator PlayPendingProgressionIfNeeded()
        {
            yield return null;
            Canvas.ForceUpdateCanvases();

            var hasPendingStarReveal = GameState.HasPendingMapStarReveal;
            var pendingStarRevealLevel = Mathf.Clamp(GameState.PendingMapStarRevealLevel, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            var pendingStarRevealCount = Mathf.Clamp(GameState.PendingMapStarRevealCount, 1, 3);

            if (!GameState.HasPendingMapProgression)
            {
                progressionPlaying = hasPendingStarReveal;
                RefreshNodeStates(hasPendingStarReveal ? pendingStarRevealLevel : 0);
                SnapScrollToLevel(hasPendingStarReveal ? pendingStarRevealLevel : GetInitialFocusLevel());
                if (hasPendingStarReveal)
                {
                    yield return new WaitForSeconds(0.18f);
                    yield return AnimateStarsForLevel(pendingStarRevealLevel, pendingStarRevealCount);
                    GameState.ClearMapStarReveal();
                    progressionPlaying = false;
                    RefreshNodeStates();
                }

                yield break;
            }

            var fromLevel = Mathf.Clamp(GameState.PendingMapProgressFrom, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            var toLevel = Mathf.Clamp(GameState.PendingMapProgressTo, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            if (toLevel <= fromLevel)
            {
                GameState.ClearMapProgression();
                yield break;
            }

            progressionPlaying = true;
            var revealCompletedLevelStars = hasPendingStarReveal && pendingStarRevealLevel == fromLevel;
            RefreshNodeStates(revealCompletedLevelStars ? fromLevel : 0);
            SnapScrollToLevel(fromLevel);
            PlaceMarkerAtLevel(fromLevel);
            if (progressLabel != null)
            {
                progressLabel.text = $"Level {fromLevel} Complete!";
            }

            yield return new WaitForSeconds(0.18f);
            if (revealCompletedLevelStars)
            {
                yield return AnimateStarsForLevel(fromLevel, pendingStarRevealCount);
                GameState.ClearMapStarReveal();
                yield return new WaitForSeconds(0.1f);
            }

            for (var level = fromLevel; level < toLevel; level++)
            {
                yield return AnimateScrollToLevel(level + 1, 0.22f);
                yield return AnimateMarker(GetMarkerPosition(level), GetMarkerPosition(level + 1));
                GameState.SelectedLevelNumber = level + 1;
                RefreshNodeStates();
                yield return PulseNode(level + 1);
                yield return new WaitForSeconds(stepPauseDuration);
            }

            if (progressLabel != null)
            {
                progressLabel.text = $"Level {toLevel} Unlocked";
            }

            GameState.ClearMapProgression();
            GameState.ClearMapStarReveal();
            progressionPlaying = false;
            RefreshNodeStates();
            yield return new WaitForSeconds(0.45f);
            if (progressLabel != null)
            {
                progressLabel.text = string.Empty;
            }
        }

        private IEnumerator AnimateMarker(Vector2 from, Vector2 to)
        {
            if (playerMarkerRect == null)
            {
                yield break;
            }

            var markerRect = playerMarkerRect;
            for (var elapsed = 0f; elapsed < stepAnimationDuration; elapsed += Time.unscaledDeltaTime)
            {
                var t = Mathf.Clamp01(elapsed / stepAnimationDuration);
                var eased = EaseInOut(t);
                var arc = Mathf.Sin(t * Mathf.PI) * 56f;
                var position = Vector2.Lerp(from, to, eased) + new Vector2(0f, arc);
                if (usesSceneEditableMap)
                {
                    markerRect.localPosition = new Vector3(position.x, position.y, markerRect.localPosition.z);
                }
                else
                {
                    markerRect.anchoredPosition = position;
                }

                markerRect.localScale = playerMarkerBaseScale * (1f + Mathf.Sin(t * Mathf.PI) * 0.12f);
                yield return null;
            }

            if (usesSceneEditableMap)
            {
                markerRect.localPosition = new Vector3(to.x, to.y, markerRect.localPosition.z);
            }
            else
            {
                markerRect.anchoredPosition = to;
            }

            markerRect.localScale = playerMarkerBaseScale;
            SpawnMapBurst(to, new Color(1f, 0.88f, 0.28f, 1f), 16, 82f);
            HapticsManager.Medium();
        }

        private IEnumerator PulseNode(int levelNumber)
        {
            if (!nodeViews.TryGetValue(levelNumber, out var view))
            {
                yield break;
            }

            var rect = view.Button.GetComponent<RectTransform>();
            var baseScale = view.BaseScale == Vector3.zero ? Vector3.one : view.BaseScale;
            for (var elapsed = 0f; elapsed < 0.32f; elapsed += Time.unscaledDeltaTime)
            {
                var t = Mathf.Clamp01(elapsed / 0.32f);
                rect.localScale = baseScale * (1f + Mathf.Sin(t * Mathf.PI) * 0.18f);
                yield return null;
            }

            rect.localScale = baseScale;
            var burstPosition = usesSceneEditableMap ? GetSceneEditableLevelLocalPosition(levelNumber) : rect.anchoredPosition;
            SpawnMapBurst(burstPosition, new Color(0.35f, 0.78f, 1f, 1f), 14, 76f);
        }

        private IEnumerator AnimateStarsForLevel(int levelNumber, int stars)
        {
            if (!nodeViews.TryGetValue(levelNumber, out var view) || view.StarsLabel == null)
            {
                yield break;
            }

            stars = Mathf.Clamp(stars, 1, 3);
            var rect = view.StarsLabel.rectTransform;
            var baseScale = rect.localScale == Vector3.zero ? Vector3.one : rect.localScale;
            view.StarsLabel.text = string.Empty;
            view.StarsLabel.color = new Color(1f, 0.86f, 0.18f, 1f);
            view.StarsLabel.transform.SetAsLastSibling();

            for (var visibleStars = 1; visibleStars <= stars; visibleStars++)
            {
                view.StarsLabel.text = BuildStarText(visibleStars);
                var burstPosition = usesSceneEditableMap
                    ? GetSceneEditableLevelLocalPosition(levelNumber) + new Vector2(0f, -66f)
                    : GetLevelPosition(levelNumber) + new Vector2(0f, -66f);
                SpawnMapBurst(burstPosition, new Color(1f, 0.86f, 0.18f, 1f), 8 + visibleStars * 3, 62f);
                HapticsManager.Light();
                for (var elapsed = 0f; elapsed < 0.22f; elapsed += Time.unscaledDeltaTime)
                {
                    var t = Mathf.Clamp01(elapsed / 0.22f);
                    var bounce = 1f + Mathf.Sin(t * Mathf.PI) * 0.45f;
                    rect.localScale = baseScale * bounce;
                    yield return null;
                }

                rect.localScale = baseScale;
                yield return new WaitForSeconds(0.08f);
            }

            yield return PulseNode(levelNumber);
        }

        private IEnumerator AnimateScrollToLevel(int levelNumber, float duration)
        {
            if (usesSceneEditableMap || scrollRect == null || contentRoot == null)
            {
                yield break;
            }

            Canvas.ForceUpdateCanvases();
            var start = contentRoot.anchoredPosition;
            var target = new Vector2(start.x, GetScrollYForLevel(levelNumber));
            for (var elapsed = 0f; elapsed < duration; elapsed += Time.unscaledDeltaTime)
            {
                var t = Mathf.Clamp01(elapsed / duration);
                contentRoot.anchoredPosition = Vector2.Lerp(start, target, EaseInOut(t));
                yield return null;
            }

            contentRoot.anchoredPosition = target;
        }

        private void RefreshNodeStates(int suppressStarsForLevel = 0)
        {
            if (usesSceneEditableMap)
            {
                RefreshSceneEditableMapButtons();
                return;
            }

            highlightedLevelNumber = 0;
            foreach (var pair in nodeViews)
            {
                var levelNumber = pair.Key;
                var view = pair.Value;
                var unlocked = CanPlayLevel(levelNumber) && SaveManager.IsLevelUnlocked(levelNumber);
                var current = unlocked && levelNumber == GetSelectedOrUnlockedLevel();
                var stars = SaveManager.GetStars(levelNumber);
                var completed = unlocked && stars > 0;
                if (current)
                {
                    highlightedLevelNumber = levelNumber;
                }

                view.Button.interactable = unlocked && !progressionPlaying;
                view.Image.sprite = current && currentNodeSprite != null
                    ? currentNodeSprite
                    : completed && completedNodeSprite != null
                        ? completedNodeSprite
                        : unlocked && unlockedNodeSprite != null
                            ? unlockedNodeSprite
                            : !unlocked && lockedNodeSprite != null
                                ? lockedNodeSprite
                                : null;
                view.Image.color = view.Image.sprite != null
                    ? Color.white
                    : current
                        ? new Color(0.2f, 0.68f, 1f, 0.98f)
                        : completed
                            ? new Color(0.46f, 0.82f, 0.16f, 0.98f)
                            : unlocked
                                ? new Color(0.23f, 0.66f, 0.94f, 0.98f)
                                : new Color(0.45f, 0.48f, 0.57f, 0.86f);

                view.NumberLabel.text = unlocked ? levelNumber.ToString() : "?";
                view.NumberLabel.fontSize = unlocked ? 48 : 40;
                view.NumberLabel.resizeTextMaxSize = unlocked ? 48 : 40;
                view.NumberLabel.resizeTextMinSize = unlocked ? 25 : 14;
                view.NumberLabel.color = unlocked ? Color.white : new Color(0.9f, 0.86f, 0.78f, 0.82f);
                var displayStars = levelNumber == suppressStarsForLevel ? 0 : stars;
                view.StarsLabel.text = unlocked && displayStars > 0 ? BuildStarText(displayStars) : string.Empty;
                view.StarsLabel.rectTransform.localScale = Vector3.one;
                view.BadgeLabel.text = string.Empty;
                view.BadgeLabel.color = Color.white;
                if (view.BadgePlate != null)
                {
                    view.BadgePlate.enabled = false;
                }

                if (view.Glow != null)
                {
                    view.Glow.enabled = current;
                    view.Glow.color = current ? new Color(1f, 0.88f, 0.28f, 0.2f) : Color.clear;
                    view.Glow.rectTransform.localScale = Vector3.one;
                }
            }

            PlaceMarkerAtLevel(GetSelectedOrUnlockedLevel());
            playerMarker?.transform.SetAsLastSibling();
            progressLabel?.transform.SetAsLastSibling();
        }

        private void PlaceMarkerAtLevel(int levelNumber)
        {
            if (playerMarkerRect == null)
            {
                return;
            }

            var position = GetMarkerPosition(levelNumber);
            if (usesSceneEditableMap)
            {
                playerMarkerRect.localPosition = new Vector3(position.x, position.y, playerMarkerRect.localPosition.z);
            }
            else
            {
                playerMarkerRect.anchoredPosition = position;
            }
        }

        private void SnapScrollToLevel(int levelNumber)
        {
            if (usesSceneEditableMap || contentRoot == null)
            {
                return;
            }

            Canvas.ForceUpdateCanvases();
            var position = contentRoot.anchoredPosition;
            position.y = GetScrollYForLevel(levelNumber);
            contentRoot.anchoredPosition = position;
        }

        private float GetScrollYForLevel(int levelNumber)
        {
            var viewport = scrollRect != null && scrollRect.viewport != null ? scrollRect.viewport : (RectTransform)contentRoot.parent;
            var viewportHeight = viewport.rect.height > 1f ? viewport.rect.height : 1500f;
            var contentHeight = contentRoot.rect.height > 1f ? contentRoot.rect.height : contentRoot.sizeDelta.y;
            var levelPosition = GetLevelPosition(levelNumber);
            var target = -levelPosition.y - viewportHeight * 0.52f;
            return Mathf.Clamp(target, 0f, Mathf.Max(0f, contentHeight - viewportHeight));
        }

        private int GetInitialFocusLevel()
        {
            return Mathf.Clamp(GetSelectedOrUnlockedLevel(), CharacterMatch3Constants.FirstLevel, maxLevelNumber);
        }

        private int GetSelectedOrUnlockedLevel()
        {
            var selected = Mathf.Clamp(GameState.SelectedLevelNumber, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            if (CanPlayLevel(selected) && SaveManager.IsLevelUnlocked(selected))
            {
                return selected;
            }

            var highest = Mathf.Clamp(SaveManager.Data.highestUnlockedLevel, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            for (var levelNumber = highest; levelNumber >= CharacterMatch3Constants.FirstLevel; levelNumber--)
            {
                if (CanPlayLevel(levelNumber) && SaveManager.IsLevelUnlocked(levelNumber))
                {
                    return levelNumber;
                }
            }

            return CharacterMatch3Constants.FirstLevel;
        }

        private bool CanPlayLevel(int levelNumber)
        {
            return levelLibrary == null || levelLibrary.GetLevel(levelNumber) != null;
        }

        private Vector2 GetLevelPosition(int levelNumber)
        {
            var clamped = Mathf.Clamp(levelNumber, CharacterMatch3Constants.FirstLevel, maxLevelNumber);
            var zeroBased = clamped - CharacterMatch3Constants.FirstLevel;
            var sectionFromBottom = zeroBased / LevelsPerMapSegment;
            var localIndex = zeroBased % LevelsPerMapSegment;
            var localPosition = GetLevelPositionFactor(sectionFromBottom, localIndex);
            var x = GetMapViewportWidth() * localPosition.x;
            var y = GetSegmentTopY(sectionFromBottom) - GetSegmentHeight(sectionFromBottom) * localPosition.y;
            return new Vector2(x, y);
        }

        private Vector2 GetLevelPositionFactor(int segmentFromBottom, int localIndex)
        {
            var factors = GetLevelPositionFactors(segmentFromBottom);
            if (factors == null || factors.Length == 0)
            {
                return new Vector2(0.5f, 0.5f);
            }

            return factors[Mathf.Clamp(localIndex, 0, factors.Length - 1)];
        }

        private Vector2[] GetLevelPositionFactors(int segmentFromBottom)
        {
            return GetSegmentThemeIndex(segmentFromBottom) switch
            {
                0 => forestLevelPositionFactors,
                1 => beachLevelPositionFactors,
                _ => desertLevelPositionFactors
            };
        }

        private Vector2 GetMarkerPosition(int levelNumber)
        {
            if (usesSceneEditableMap)
            {
                return GetSceneEditableLevelLocalPosition(levelNumber) + SceneMarkerOffset;
            }

            return GetLevelPosition(levelNumber) + new Vector2(0f, 82f);
        }

        private Vector2 GetSceneEditableLevelLocalPosition(int levelNumber)
        {
            if (!nodeViews.TryGetValue(levelNumber, out var view) || view.Rect == null || contentRoot == null)
            {
                return Vector2.zero;
            }

            var worldCenter = view.Rect.TransformPoint(view.Rect.rect.center);
            var localCenter = contentRoot.InverseTransformPoint(worldCenter);
            return new Vector2(localCenter.x, localCenter.y);
        }

        private void AnimateCurrentLevelGlow()
        {
            if (highlightedLevelNumber <= 0 || !nodeViews.TryGetValue(highlightedLevelNumber, out var view) || view.Glow == null || !view.Glow.enabled)
            {
                return;
            }

            var pulse = 0.5f + 0.5f * Mathf.Sin(Time.unscaledTime * 3.2f);
            view.Glow.rectTransform.localScale = Vector3.one * Mathf.Lerp(0.98f, 1.1f, pulse);
            view.Glow.rectTransform.localRotation = Quaternion.Euler(0f, 0f, Mathf.Sin(Time.unscaledTime * 1.6f) * 4f);
            var color = view.Glow.color;
            color.a = Mathf.Lerp(0.12f, 0.28f, pulse);
            view.Glow.color = color;
        }

        private void AnimateIdleMarker()
        {
            if (usesSceneEditableMap || playerMarkerRect == null || progressionPlaying)
            {
                return;
            }

            var pulse = 1f + Mathf.Sin(Time.unscaledTime * 2.4f) * 0.035f;
            playerMarkerRect.localScale = playerMarkerBaseScale * pulse;
        }

        private void SpawnMapBurst(Vector2 position, Color color, int particleCount, float radius)
        {
            if (contentRoot == null || particleCount <= 0)
            {
                return;
            }

            StartCoroutine(AnimateMapBurst(position, color, particleCount, radius));
        }

        private IEnumerator AnimateMapBurst(Vector2 position, Color color, int particleCount, float radius)
        {
            var root = new GameObject("MapBurst", typeof(RectTransform));
            root.transform.SetParent(contentRoot, false);
            var rootRect = root.GetComponent<RectTransform>();
            rootRect.anchorMin = usesSceneEditableMap ? new Vector2(0.5f, 0f) : new Vector2(0f, 1f);
            rootRect.anchorMax = rootRect.anchorMin;
            rootRect.pivot = new Vector2(0.5f, 0.5f);
            rootRect.anchoredPosition = position;
            rootRect.sizeDelta = Vector2.zero;
            root.transform.SetAsLastSibling();

            var rects = new RectTransform[particleCount];
            var images = new Image[particleCount];
            for (var i = 0; i < particleCount; i++)
            {
                var particle = UIFactory.CreateImage($"MapParticle_{i:00}", root.transform, ShiftMapBurstColor(color, i));
                particle.raycastTarget = false;
                var rect = particle.rectTransform;
                rect.anchorMin = new Vector2(0.5f, 0.5f);
                rect.anchorMax = new Vector2(0.5f, 0.5f);
                rect.pivot = new Vector2(0.5f, 0.5f);
                rect.sizeDelta = Vector2.one * (10f + i % 4 * 3f);
                rect.localRotation = Quaternion.Euler(0f, 0f, i * 29f);
                rects[i] = rect;
                images[i] = particle;
            }

            const float duration = 0.42f;
            for (var elapsed = 0f; elapsed < duration; elapsed += Time.unscaledDeltaTime)
            {
                var t = Mathf.Clamp01(elapsed / duration);
                var eased = EaseOutCubic(t);
                for (var i = 0; i < particleCount; i++)
                {
                    var angle = i / (float)particleCount * Mathf.PI * 2f + 0.25f;
                    var direction = new Vector2(Mathf.Cos(angle), Mathf.Sin(angle));
                    rects[i].anchoredPosition = direction * radius * Mathf.Lerp(0.18f, 1f, eased);
                    rects[i].localRotation = Quaternion.Euler(0f, 0f, i * 29f + 230f * t);
                    rects[i].localScale = Vector3.one * Mathf.Lerp(1.18f, 0.18f, t);
                    var particleColor = images[i].color;
                    particleColor.a = Mathf.Lerp(1f, 0f, t);
                    images[i].color = particleColor;
                }

                yield return null;
            }

            Destroy(root);
        }

        private static Color ShiftMapBurstColor(Color color, int index)
        {
            var tint = 0.84f + index % 4 * 0.07f;
            return new Color(
                Mathf.Clamp01(color.r * tint + 0.08f),
                Mathf.Clamp01(color.g * tint + 0.08f),
                Mathf.Clamp01(color.b * tint + 0.08f),
                1f);
        }

        private static Color GetSparkleColor(int index)
        {
            switch (index % 5)
            {
                case 0:
                    return new Color(1f, 0.9f, 0.28f, 0.36f);
                case 1:
                    return new Color(0.48f, 0.88f, 1f, 0.32f);
                case 2:
                    return new Color(1f, 0.58f, 0.42f, 0.3f);
                case 3:
                    return new Color(0.52f, 0.92f, 0.52f, 0.32f);
                default:
                    return new Color(0.86f, 0.62f, 1f, 0.28f);
            }
        }

        private static void SetButtonColors(Button button, Color color, Color textColor)
        {
            if (button == null)
            {
                return;
            }

            var image = button.GetComponent<Image>();
            if (image != null)
            {
                image.color = color;
            }

            var colors = button.colors;
            colors.normalColor = color;
            colors.highlightedColor = Color.Lerp(color, Color.white, 0.18f);
            colors.pressedColor = Color.Lerp(color, Color.black, 0.18f);
            colors.selectedColor = Color.Lerp(color, Color.white, 0.08f);
            colors.disabledColor = new Color(color.r * 0.6f, color.g * 0.6f, color.b * 0.6f, 0.58f);
            colors.colorMultiplier = 1f;
            colors.fadeDuration = 0.08f;
            button.colors = colors;

            var label = button.GetComponentInChildren<Text>();
            if (label != null)
            {
                label.color = textColor;
                label.fontStyle = FontStyle.Bold;
            }
        }

        private static string BuildStarText(int stars)
        {
            stars = Mathf.Clamp(stars, 0, 3);
            return stars > 0 ? new string(FilledStarCharacter, stars) : string.Empty;
        }

        private static float EaseInOut(float t)
        {
            return t * t * (3f - 2f * t);
        }

        private static float EaseOutCubic(float t)
        {
            var inverse = 1f - t;
            return 1f - inverse * inverse * inverse;
        }
    }
}
