using System.Collections;
using CharacterMatch3.Board;
using CharacterMatch3.Goals;
using CharacterMatch3.Input;
using CharacterMatch3.Save;
using CharacterMatch3.Tutorial;
using CharacterMatch3.UI;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace CharacterMatch3.Core
{
    public sealed class GameSession : MonoBehaviour
    {
        [Header("Generated by setup")]
        [SerializeField] private CharacterCatalog characterCatalog;
        [SerializeField] private LevelLibrary levelLibrary;
        [SerializeField] private ScoringConfig scoringConfig;
        [SerializeField] private Match3InputSettings inputSettings;

        private readonly GoalManager goalManager = new GoalManager();
        private readonly ScoreManager scoreManager = new ScoreManager();
        private readonly MoveManager moveManager = new MoveManager();

        private GameplayUI gameplayUI;
        private BoardController boardController;
        private TutorialManager tutorialManager;
        private LevelDefinition level;
        private bool gameEnded;

        public LevelDefinition CurrentLevel => level;
        public GoalManager Goals => goalManager;
        public ScoreManager Score => scoreManager;
        public MoveManager Moves => moveManager;
        public BoardController Board => boardController;

        public void Configure(CharacterCatalog catalog, LevelLibrary library, ScoringConfig scoring, Match3InputSettings input = null)
        {
            characterCatalog = catalog;
            levelLibrary = library;
            scoringConfig = scoring;
            inputSettings = input;
        }

        private void Start()
        {
            RuntimeSceneUtility.EnsureMainCamera();
            Application.targetFrameRate = 60;
            Screen.orientation = ScreenOrientation.Portrait;
            SaveManager.Load();
            EnsureSceneObjects();
            LoadSelectedLevel();
            if (level == null)
            {
                level = CreateEmergencyLevel();
            }

            gameplayUI.Initialize(this, characterCatalog);
            gameplayUI.BoardView.SetInputSettings(inputSettings);
            StartLevel();
        }

        public void StartLevel()
        {
            if (level == null)
            {
                Debug.LogError("No Character Match-3 level selected.");
                return;
            }

            gameEnded = false;
            scoreManager.Reset();
            moveManager.Reset(level.moveLimit);
            goalManager.Initialize(level);
            gameplayUI.BindGoalManager(goalManager);
            gameplayUI.UpdateScore(scoreManager.Score);
            gameplayUI.UpdateMoves(moveManager.MovesRemaining);
            gameplayUI.HideAllPanels();
            gameplayUI.BoardView.SetInputSettings(inputSettings);

            boardController.Initialize(level, characterCatalog, scoringConfig, gameplayUI.BoardView);
            boardController.ValidMoveMade += OnValidMoveMade;
            boardController.BoardSettled += CheckEndState;
            boardController.PieceRemoved += OnPieceRemoved;
            boardController.SoftCoverLayerRemoved += _ => goalManager.RecordSoftCoverCleared();
            boardController.CrateLayerRemoved += _ => goalManager.RecordCrateLayerBroken();
            boardController.CompanionDelivered += _ => goalManager.RecordCompanionDelivered();
            boardController.ScoreAwarded += OnScoreAwarded;

            tutorialManager.BeginIfNeeded(level, boardController);
        }

        public void RestartLevel()
        {
            GameState.ClearMapProgression();
            SceneManager.LoadScene("Gameplay");
        }

        public void ExitToMap()
        {
            SceneManager.LoadScene("LevelMap");
        }

        public void PlayNextLevel()
        {
            QueueMapProgressionToNextLevel();
            SceneManager.LoadScene("LevelMap");
        }

        public void Pause()
        {
            if (gameEnded)
            {
                return;
            }

            boardController?.SetInputLocked(true);
            gameplayUI.ShowPausePanel();
        }

        public void Resume()
        {
            boardController?.SetInputLocked(false);
            gameplayUI.HideAllPanels();
        }

        public void ShowSettings()
        {
            gameplayUI.ShowSettingsPanel();
        }

        public void SetMusicEnabled(bool enabled)
        {
            SaveManager.SetMusicEnabled(enabled);
        }

        public void SetSoundEnabled(bool enabled)
        {
            SaveManager.SetSoundEnabled(enabled);
        }

        public void SetHapticsEnabled(bool enabled)
        {
            SaveManager.SetHapticsEnabled(enabled);
        }

        private void OnValidMoveMade()
        {
            if (moveManager.TryConsumeMove())
            {
                gameplayUI.UpdateMoves(moveManager.MovesRemaining);
                tutorialManager.MarkCurrentTutorialComplete();
            }
        }

        private void OnPieceRemoved(CharacterType character, PieceKind kind, BoardCoordinate coordinate)
        {
            if (kind != PieceKind.Companion)
            {
                goalManager.RecordPieceCollected(character);
            }
        }

        private void OnScoreAwarded(int amount, BoardCoordinate coordinate)
        {
            scoreManager.AddScore(amount);
            goalManager.RecordScore(scoreManager.Score);
            gameplayUI.UpdateScore(scoreManager.Score);
            gameplayUI.UpdateStars(level, scoreManager.Score);
        }

        private void CheckEndState()
        {
            if (gameEnded)
            {
                return;
            }

            if (goalManager.AreAllGoalsComplete())
            {
                StartCoroutine(WinFlow());
            }
            else if (moveManager.MovesRemaining <= 0)
            {
                StartCoroutine(LoseFlow());
            }
        }

        private IEnumerator WinFlow()
        {
            gameEnded = true;
            boardController.SetInputLocked(true);
            var remaining = moveManager.ConsumeAllRemaining();
            if (scoringConfig != null && remaining > 0)
            {
                scoreManager.AddScore(remaining * scoringConfig.remainingMoveBonus);
                goalManager.RecordScore(scoreManager.Score);
            }

            gameplayUI.UpdateMoves(moveManager.MovesRemaining);
            gameplayUI.UpdateScore(scoreManager.Score);
            gameplayUI.UpdateStars(level, scoreManager.Score);
            yield return new WaitForSeconds(0.35f);

            var stars = Mathf.Max(1, scoreManager.GetStars(level));
            SaveManager.RecordLevelWin(level.levelNumber, scoreManager.Score, stars);
            QueueMapProgressionToNextLevel();
            AudioManager.Instance?.Play(AudioManager.Instance.win);
            gameplayUI.ShowWinPanel(scoreManager.Score, stars);
        }

        private void QueueMapProgressionToNextLevel()
        {
            if (level == null || level.levelNumber >= CharacterMatch3Constants.LastLevel)
            {
                GameState.SelectedLevelNumber = level != null ? level.levelNumber : GameState.SelectedLevelNumber;
                GameState.ClearMapProgression();
                return;
            }

            var nextLevel = Mathf.Min(CharacterMatch3Constants.LastLevel, level.levelNumber + 1);
            if (SaveManager.IsLevelUnlocked(nextLevel))
            {
                GameState.QueueMapProgression(level.levelNumber, nextLevel);
            }
            else
            {
                GameState.SelectedLevelNumber = level.levelNumber;
                GameState.ClearMapProgression();
            }
        }

        private IEnumerator LoseFlow()
        {
            gameEnded = true;
            boardController.SetInputLocked(true);
            yield return new WaitForSeconds(0.35f);
            AudioManager.Instance?.Play(AudioManager.Instance.lose);
            gameplayUI.ShowLosePanel(scoreManager.Score);
        }

        private void LoadSelectedLevel()
        {
            level = levelLibrary != null ? levelLibrary.GetLevel(GameState.SelectedLevelNumber) : null;
            var levels = levelLibrary != null ? levelLibrary.Levels : null;
            if (level == null && levels != null && levels.Count > 0)
            {
                level = levels[0];
                if (level != null)
                {
                    GameState.SelectedLevelNumber = level.levelNumber;
                }
            }

            if (level == null)
            {
                Debug.LogError("Character Match-3 could not find a LevelDefinition. Run Character Match-3 > Setup Complete Game.");
            }
        }

        private static LevelDefinition CreateEmergencyLevel()
        {
            var fallback = ScriptableObject.CreateInstance<LevelDefinition>();
            fallback.levelNumber = 1;
            fallback.displayName = "Emergency Level";
            fallback.boardWidth = 7;
            fallback.boardHeight = 7;
            fallback.moveLimit = 30;
            fallback.randomSeed = 1001;
            fallback.availableCharacterTypes.Clear();
            fallback.availableCharacterTypes.Add(CharacterType.Cat);
            fallback.availableCharacterTypes.Add(CharacterType.Bunny);
            fallback.availableCharacterTypes.Add(CharacterType.Dino);
            fallback.availableCharacterTypes.Add(CharacterType.Penguin);
            fallback.goals.Clear();
            fallback.goals.Add(new LevelGoalData(CharacterType.Cat, 8));
            fallback.oneStarScore = 2000;
            fallback.twoStarScore = 4000;
            fallback.threeStarScore = 7000;
            fallback.EnsureDefaults();
            return fallback;
        }

        private void EnsureSceneObjects()
        {
            gameplayUI = GetComponent<GameplayUI>();
            if (gameplayUI == null)
            {
                gameplayUI = gameObject.AddComponent<GameplayUI>();
            }

            boardController = GetComponent<BoardController>();
            if (boardController == null)
            {
                boardController = gameObject.AddComponent<BoardController>();
            }

            tutorialManager = GetComponent<TutorialManager>();
            if (tutorialManager == null)
            {
                tutorialManager = gameObject.AddComponent<TutorialManager>();
            }

            if (AudioManager.Instance == null)
            {
                new GameObject("AudioManager").AddComponent<AudioManager>();
            }
        }
    }
}
